config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :create]
  resources :weapons

  root 'weapons#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  enum kind: [ :knight, :wizard ]
  validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 99 }

  def title
    "#{self.kind} #{self.nickname} ##{self.level}"
  end
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  validates :level, numericality: { greater_than: 0 }, allow_nil: false, presence: true

  def current_power
    ((level - 1) * power_step) + power_base
  end

  def title
    "#{name} ##{level}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def create
    @user = User.create(user_params)
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:nickname, :kind, :level)
    end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  def index
    @weapons = Weapon.all
  end

  def new
    @weapon = Weapon.new
  end

  def create
    @weapon = Weapon.create(weapon_params)

    if @weapon.save
      redirect_to weapons_path
    else
      render :new
    end
  end

  def destroy
    @weapon = Weapon.find(params[:id])
    @weapon.destroy

    redirect_to root_path
  end

  def show
    @weapon = Weapon.find(params[:id])
  end

  private
    def weapon_params
      params.require(:weapons).permit(:name, :description, :power_base, :power_step, :level)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestLikeAHero</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <p><%= user.title %></p>
<% end %>

app/views/weapons/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/weapons/index.html.erb
<div>
  <h1>List weapons</h1>
  <ul>
    <% @weapons.each do |weapon| %>
      <li>Title: <%= link_to weapon.title, weapon_path(weapon) %> - <span>Current power: <%=weapon.current_power%></span></li>
      <li><%= link_to weapon.title, weapon_path(weapon) %></li>
    <% end %>
  </ul>
</div>

app/views/weapons/new.html.erb
<div>
  <h1>List weapons</h1>
</div>

app/views/weapons/show.html.erb
<div class="container">
  <h1>Current weapon</h1>

  <p>Title: <%= @weapon.title %></p>
  <p>Name: <%= @weapon.name %></p>
  <p>Description: <%= @weapon.description%></p>
  <p>Power base: <%= @weapon.power_base %></p>
  <p>Power step: <%= @weapon.power_step %></p>
  <p>Level: <%= @weapon.level %></p>
</div>